### ISSUE TITLE
希望文档可以详细一点

### ISSUE THREAD

**Issue by Mr-ShiHuaYu** [NHZEX/think-blade#5]
因为从laravel迁移过来，一些@can指令不能用，希望可以有详细一点的文档

**Comment by NHZEX** [comment]
看这里源码：`lib/view/Compilers/Concerns/CompilesAuthorizations.php`，容器你会用就没问题。

**Comment by Mr-ShiHuaYu** [comment]
好的，已经成功了，谢谢
