### ISSUE TITLE
加载后直接报错了

### ISSUE THREAD

**Issue by coolxitech** [NHZEX/think-blade#6]
During inheritance of ArrayAccess: Uncaught think\exception\ErrorException: Return type of Illuminate\View\View::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\Project\domainff\vendor\nhzex\think-blade\lib\view\View.php:309 Stack trace: #0 D:\Project\domainff\vendor\nhzex\think-blade\lib\view\View.php(19)

**Comment by NHZEX** [comment]
使用新版本可解决
